version: '3'
# Panda DevOps: Class 3: First docker-compose exercise.

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkinscompose
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - ../volumes/jenkins:/var/jenkins_home
    networks:
      - docker_network
  
  ubuntu:
    container_name: ubuntucompose
    build: ../dockerfiles/slave/
    depends_on:
      - "jenkins"
    networks:
      - docker_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # I put this command in the dockerfile.
    #command: java -jar agent.jar -jnlpUrl http://jenkinscompose...itd
    command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/ubuntuslave/jenkins-agent.jnlp -secret 46fe1ff1912808b45f59929367315c60db5031d8214373e5aacc65d2d60e022e -workDir "/home/"

  selenium_hub:
    image: selenium/hub
    container_name: selenium-hubcompose
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    networks:
      - docker_network

  selenium_node:
    image: selenium/node-firefox
    container_name: firefoxcompose
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hubcompose
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
    networks:
      - docker_network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactorycompose
    volumes:
      - ../volumes/artifactory:/var/opt/jfrog/artifactory
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - docker_network



networks:
  docker_network:
    driver: bridge
